require 'rspec'

require_relative '../lib/models/Person'
require_relative '../lib/models/Student'
require_relative '../lib/models/Teacher'
require_relative '../lib/models/Rental'
require_relative '../lib/models/Book'
require_relative '../lib/models/Classroom'
require_relative '../lib/Nameable'
require_relative '../lib/BaseDecorator'
require_relative '../lib/TrimmerDecorator'
require_relative '../lib/CapitalizeDecorator'
